export const APP_STRINGS = {
  MED_FLOW_HOME: "MedFlow Home",
  LOGIN: "Login",
  SIGN_UP_SCREEN: "SignUpScreen",
  CONFIRM_SCREEN: "Confirm",
  HOME: "Home",
  LOGOUT: "Logout",
  START_SCREEN: "Start",
  SAFE_CAMP_LOGO_URL: "https://mashghol.com/applogo.png",
  USER: "user",
  Settings  : "Settings",
  Phone: "phone",
  EMAIL: "Email",
  INFO: "info",
  SCAN_QR_CODE: 'Scan QR Code',
  CONFIRM_PHONE: "CONFIRM PHONE",
  QR_CODE_INFO_TXT: "What is my QR Code for?",
  EMAIL_OUTLINE: "email-outline",
  PASSWORD_LOCK: "lock1",
  PHONE_NUMBER_PLACE_HOLDERS: "Phone Number (888) 888-8888",
  FIRST_NAME_PLACE_HOLDERS: "First Name",
  LAST_NAME_PLACE_HOLDER: "Last Name",
  PASSWORD_PLACE_HOLDER: "Password",
  PASSWORD_HINT: "Password (at least 8 characters)",
  FEILD_REQUIRED: "This field is required",
  SIGN_IN_TXT: "Sign In",
  CREATE: "Create",
  QUESTIONS_LIST: "Questions List",
  NEXT: "Next",
  FACIAL_RECOGNITION: "Facial Recognition",
  BAR_CODE: "Bar Code",
  USER_NAME_EXIST_EXCEPTION:
    "UsernameExistsException: An account with the given phone_number already exists.",
  KEYBOARD_TYPES: {
    NUMBER_PAD: "number-pad",
    EMAIL_ADDRESS: "email-address",
  },
  IMAGES_TYPES: {
    ANT_DESIGN: "AntDesign",
    MATERIAL_COMMUNITY_DESIGN: "MaterialCommunityIcons",
  },
};
